let SHEET=null, DASH=null, FILTERS=null, charts={}, ruleSeq=0, CURRENT_DASH_SOURCE='full', CURRENT_DETAIL=null, DETAIL_DIRTY={};
const OPERATORS=[['contains','contains'],['equals','equals'],['not_equals','not equals'],['not_contains','does not contain'],['starts_with','starts with'],['ends_with','ends with'],['blank','is blank'],['not_blank','is not blank'],['greater_than','greater than'],['less_than','less than'],['greater_or_equal','greater or equal'],['less_or_equal','less or equal'],['date_after','date after'],['date_before','date before'],['date_on','date on']];
const titles={dashboard:['Executive Dashboard','Portfolio health, workload, aging, risk and demand throughput view.'],interrogate:['Interrogate','Build column-specific filters and drive dashboard insights from the result set.'],manager:['Manager View','Capacity, quality and readiness cockpit for daily demand management.'],capacity:['Capacity','Team workload, weighted load, overload and WIP risk view.'],risk:['Risk','Prioritised risk panel based on readiness, aging and capacity risk.'],register:['Demand Register','Select a demand, inspect all details, update fields and write back to Smartsheet.'],add:['Add Demand','Create a new demand directly in Smartsheet.']};
function show(id,btn){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(btn&&btn.tagName==='BUTTON')btn.classList.add('active');document.getElementById('pageTitle').textContent=titles[id][0];document.getElementById('pageSub').textContent=titles[id][1];}
async function loadAll(){setLoad(true);try{const [sheet,dash,sug]=await Promise.all([fetch('/api/sheet').then(ok),fetch('/api/dashboard').then(ok),fetch('/api/interrogate/suggestions').then(ok)]);SHEET=sheet;DASH=dash;FILTERS=sug.filters;CURRENT_DASH_SOURCE='full';renderDashboard();renderForm();renderTable();renderSuggestions(sug.suggestions);if(!document.querySelector('.filter-rule')) addRule();updateBanner();}catch(e){alert('Failed to load data: '+e.message)}finally{setLoad(false)}}
async function ok(r){if(!r.ok){let msg=await r.text();throw new Error(r.status+' '+r.statusText+' '+msg)}return r.json()} function setLoad(v){document.getElementById('loading').classList.toggle('on',v)}
function metric(id,val,suffix=''){document.getElementById(id).textContent=(val??0)+suffix}
function renderDashboard(){const m=DASH.metrics;metric('mTotal',m.total_demands);metric('mOpen',m.open_demands);metric('mClosed',m.closed_demands);metric('mOverdue',m.overdue_demands);metric('mAging',m.aging_over_30);metric('mAvg',m.avg_age_open,'d');metric('mReady',m.ready_percent,'%');metric('mNotReady',m.not_ready);metric('mHighRisk',m.high_risk);metric('mTeamLoad',m.team_load_percent,'%');draw('healthChart','doughnut',DASH.charts.health);draw('priorityChart','bar',DASH.charts.priority);draw('statusChart','bar',DASH.charts.status);draw('assigneeChart','bar',DASH.charts.assignee);draw('ageChart','bar',DASH.charts.age_bucket);draw('readinessChart','doughnut',DASH.charts.readiness);draw('confidenceChart','bar',DASH.charts.confidence);renderRisk();renderV8Views();updateBanner();}
function draw(id,type,items){if(charts[id])charts[id].destroy();let ctx=document.getElementById(id);charts[id]=new Chart(ctx,{type:type,data:{labels:(items||[]).map(x=>x.name),datasets:[{label:'Count',data:(items||[]).map(x=>x.value)}]},options:{responsive:true,plugins:{legend:{display:type==='doughnut'?true:false}},scales:type==='bar'?{y:{beginAtZero:true}}:{}}});}
function renderRisk(){const div=document.getElementById('riskList');if(!DASH.risk_items.length){div.innerHTML='<p class="muted">No open risk items found.</p>';return}div.innerHTML='<table><thead><tr><th>Health</th><th>Age</th><th>Key details</th></tr></thead><tbody>'+DASH.risk_items.map(x=>`<tr><td><span class="pill health-${x.health}">${x.health}</span></td><td>${x.age_days||''}</td><td>${Object.entries(x.fields).map(([k,v])=>`<b>${escapeHtml(k)}:</b> ${escapeHtml(v||'')}`).join('<br>')}</td></tr>`).join('')+'</tbody></table>';}
function updateBanner(){const b=document.getElementById('filterBanner');if(CURRENT_DASH_SOURCE==='filtered'){b.classList.add('on');b.innerHTML='Dashboard is showing the filtered Interrogate result set. Click <b>Reset Dashboard</b> to return to the full Smartsheet view.';}else{b.classList.remove('on');b.innerHTML='';}}
function clearDashboardFilter(){CURRENT_DASH_SOURCE='full';fetch('/api/dashboard').then(ok).then(d=>{DASH=d;renderDashboard();});}
function renderSuggestions(items){document.getElementById('suggestions').innerHTML=items.map(s=>`<button class="chip" onclick="quickQuery('${esc(s)}')">${escapeHtml(s)}</button>`).join('')}
function quickQuery(s){clearRules();const keys=SHEET.key_columns||{};if(s.toLowerCase().includes('overdue'))addRule('_health','equals','Overdue');else if(s.toLowerCase().includes('older than 30'))addRule('_age_days','greater_than','30');else if(s.toLowerCase().includes('blank assignee'))addRule(keys.assignee||'Assignee','blank','');else if(s.toLowerCase().includes('high priority')){addRule(keys.priority||'Priority','contains','High');addRule('_health','not_equals','Closed');}else addRule(keys.demand||SHEET.column_titles[0],'contains',s);applyFilter(true);}
function addRule(column='',operator='contains',value=''){const id=++ruleSeq;const cols=[...(SHEET?.column_titles||[]),'_health','_age_days','_age_bucket','_is_overdue','_quality_score','_readiness','_confidence'];const html=`<div class="filter-rule" data-rule="${id}"><div class="filter-head"><b>Rule ${id}</b><button class="danger mini" onclick="removeRule(${id})">Remove</button></div><div class="filterbar"><select class="rule-col">${cols.map(c=>`<option ${c===column?'selected':''}>${escapeHtml(c)}</option>`).join('')}</select><select class="rule-op">${OPERATORS.map(([v,t])=>`<option value="${v}" ${v===operator?'selected':''}>${t}</option>`).join('')}</select><input class="rule-val" placeholder="Criteria value" value="${escapeHtml(value)}"><button class="btn ghost" onclick="previewDistinct(this)">Values</button></div><div class="muted distinct-values"></div></div>`;document.getElementById('rules').insertAdjacentHTML('beforeend',html)}
function removeRule(id){document.querySelector(`[data-rule="${id}"]`)?.remove()} function clearRules(){document.getElementById('rules').innerHTML='';}
function getRules(){return [...document.querySelectorAll('.filter-rule')].map(el=>({column:el.querySelector('.rule-col').value,operator:el.querySelector('.rule-op').value,value:el.querySelector('.rule-val').value})).filter(r=>r.column && (r.value || ['blank','not_blank'].includes(r.operator)));}
async function applyFilter(updateDashboard){const rules=getRules();if(!rules.length){alert('Add at least one rule with criteria.');return}setLoad(true);try{const payload={rules,logic:document.getElementById('filterLogic').value,limit:500};const res=await fetch('/api/filter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(ok);renderFilterSummary(res.summary);renderFilterResults(res.rows,res.key_columns);document.getElementById('activeRulesText').textContent=(res.logic||'AND')+' filter: '+rules.map(r=>`${r.column} ${r.operator.replaceAll('_',' ')} ${r.value}`).join(' | ');if(updateDashboard){DASH=res.dashboard;CURRENT_DASH_SOURCE='filtered';renderDashboard();show('dashboard',document.querySelector('.nav button'));}}finally{setLoad(false)}}
function renderFilterSummary(s){metric('fMatched',s.total_demands);metric('fOpen',s.open_demands);metric('fOverdue',s.overdue_demands);metric('fAvg',s.avg_age_open+'d')}
function renderFilterResults(rows,keys){const cols=visibleCols(keys);let html='<thead><tr>'+cols.map(c=>`<th>${escapeHtml(c)}</th>`).join('')+'<th>Health</th><th>Age</th><th>Quality</th><th>Action</th></tr></thead><tbody>';html+=rows.map(r=>'<tr>'+cols.map(c=>`<td>${escapeHtml(r[c]??'')}</td>`).join('')+`<td><span class="pill health-${r._health}">${r._health||''}</span></td><td>${r._age_days||''}</td><td>${r._quality_score??''}% ${r._readiness?'<br><span class="pill">'+escapeHtml(r._readiness)+'</span>':''}</td><td><button class="btn soft mini" onclick="openDemandDetail(${r._row_id})">Open</button></td></tr>`).join('');document.getElementById('filterResults').innerHTML=html+'</tbody>';}
function previewDistinct(btn){const el=btn.closest('.filter-rule');const col=el.querySelector('.rule-col').value;const vals=[...new Set((SHEET.rows||[]).map(r=>r[col]).filter(v=>v!==undefined&&v!==null&&String(v).trim()!==''))].slice(0,25);el.querySelector('.distinct-values').innerHTML=vals.length?'<b>Sample values:</b> '+vals.map(v=>`<button class="chip mini" onclick="setRuleValue(this,'${esc(v)}')">${escapeHtml(v)}</button>`).join(' '):'No sample values found.'}
function setRuleValue(btn,v){btn.closest('.filter-rule').querySelector('.rule-val').value=v;}

function renderV8Views(){
 const v8=(DASH&&DASH.v8)||{}; const sum=v8.summary||{}; const cap=(v8.capacity||{}).team||[]; const rows=v8.rows||[];
 metric('mgrReady',sum.ready); metric('mgrNeeds',sum.needs_clarification); metric('mgrNotReady',sum.not_ready); metric('mgrOverloaded',sum.overloaded_resources);
 renderCapacityTable(cap); renderManagerQueue(rows); renderDecisionMatrix(sum,cap); renderManagerInsights(sum,cap); renderV8Risk(v8.risk_items||[]);
}
function riskClass(r){return r==='High'?'health-Overdue':(r==='Medium'?'health-Aging':'health-Healthy')}
function renderCapacityTable(team){let html='<thead><tr><th>Assignee</th><th>Active</th><th>Overdue</th><th>Avg Age</th><th>Weighted Load</th><th>Load %</th><th>Risk</th><th>Action</th></tr></thead><tbody>';
 html+=team.map(r=>`<tr><td>${escapeHtml(r.assignee)}</td><td>${r.active}</td><td>${r.overdue}</td><td>${r.avg_age}d</td><td>${r.weighted_load}</td><td><b>${r.load_percent}%</b></td><td><span class="pill ${riskClass(r.risk)}">${r.risk}</span></td><td><button class="btn soft mini" onclick="filterAssignee('${esc(r.assignee)}')">View Demands</button></td></tr>`).join('');
 document.getElementById('capacityTable').innerHTML=html+'</tbody>';
}
function filterAssignee(name){show('interrogate',document.querySelectorAll('.nav button')[1]);clearRules();addRule((SHEET.key_columns||{}).assignee||'Assignee','equals',name);applyFilter(true);}
function renderManagerQueue(rows){const keys=(SHEET&&SHEET.key_columns)||{};const cols=visibleCols(keys).slice(0,6);let html='<thead><tr>'+cols.map(c=>`<th>${escapeHtml(c)}</th>`).join('')+'<th>Quality</th><th>Readiness</th><th>Confidence</th><th>Reason</th><th>Action</th></tr></thead><tbody>';
 html+=rows.slice(0,120).map(r=>'<tr>'+cols.map(c=>`<td>${escapeHtml(r[c]??'')}</td>`).join('')+`<td><b>${r._quality_score??''}%</b></td><td><span class="pill ${r._readiness==='Ready'?'health-Healthy':(r._readiness==='Not Ready'?'health-Overdue':'health-Aging')}">${escapeHtml(r._readiness||'')}</span></td><td>${escapeHtml(r._confidence||'')}</td><td>${escapeHtml(r._quality_reason||'')}</td><td><button class="btn soft mini" onclick="openDemandDetail(${r._row_id})">Open</button></td></tr>`).join('');
 document.getElementById('managerQueue').innerHTML=html+'</tbody>';
}
function renderDecisionMatrix(sum,cap){const load=sum.team_load_percent||0;const ready=sum.ready_percent||0;let quality=ready>=70?'High':(ready>=40?'Medium':'Low');let capacity=load<65?'Low':(load<100?'Medium':'High');let decision='';if(quality==='High'&&capacity==='Low')decision='🟢 Ready for planning';else if(quality==='High'&&capacity==='High')decision='🔴 Good quality but overloaded';else if(quality==='Low'&&capacity==='High')decision='🔴 Critical: poor quality + overloaded';else if(quality==='Low')decision='⚠️ Improve demand quality before commitment';else decision='🟡 Watch and prioritise';document.getElementById('decisionMatrix').innerHTML=`<div class="summary-strip"><div><span class="label">Quality</span><b>${quality}</b></div><div><span class="label">Capacity</span><b>${capacity}</b></div><div><span class="label">Decision</span><b style="font-size:18px">${decision}</b></div><div><span class="label">Team Load</span><b>${load}%</b></div></div><p class="muted">Matrix uses readiness percentage and weighted team load from active Smartsheet demands.</p>`;}
function renderManagerInsights(sum,cap){let txt=[];if(sum.not_ready)txt.push(`<b>${sum.not_ready}</b> demands are not ready for planning.`);if(sum.needs_clarification)txt.push(`<b>${sum.needs_clarification}</b> need clarification.`);if(sum.overloaded_resources)txt.push(`<b>${sum.overloaded_resources}</b> resources are overloaded.`);if(sum.high_risk)txt.push(`<b>${sum.high_risk}</b> high-risk demands need manager attention.`);if(!txt.length)txt.push('The current demand set looks stable based on quality, aging and capacity indicators.');document.getElementById('managerInsights').innerHTML='<ul><li>'+txt.join('</li><li>')+'</li></ul>';}
function renderV8Risk(items){let html=(items||[]).map(x=>`<div class="card result-card"><b>Row ${x.row_number||''} · Quality ${x.quality_score}% · ${escapeHtml(x.readiness)}</b><p class="muted">Confidence: ${escapeHtml(x.confidence)} · Capacity Risk: ${escapeHtml(x.capacity_risk)}</p><p>${escapeHtml(x.reason||'')}</p><button class="btn soft mini" onclick="openDemandDetail(${x.row_id})">Open Demand</button></div>`).join('');document.getElementById('v8RiskList').innerHTML=html||'<p class="muted">No risk items found.</p>';}

function renderTable(){if(!SHEET)return;let q=(document.getElementById('tableSearch')?.value||'').toLowerCase();let limit=parseInt(document.getElementById('visibleLimit')?.value||'100');let rows=SHEET.rows.filter(r=>!q||Object.values(r).join(' ').toLowerCase().includes(q)).slice(0,limit);let cols=visibleCols();let html='<thead><tr>'+cols.map(c=>`<th>${escapeHtml(c)}</th>`).join('')+'<th>Health</th><th>Actions</th></tr></thead><tbody>';for(const r of rows){html+='<tr>'+cols.map(c=>`<td>${escapeHtml(r[c]??'')}</td>`).join('')+`<td><span class="pill health-${r._health}">${r._health||''}</span></td><td><button class="btn soft mini" onclick="openDemandDetail(${r._row_id})">Open / Edit</button> <button class="danger mini" onclick="deleteRow(${r._row_id})">Delete</button></td></tr>`}document.getElementById('rowsTable').innerHTML=html+'</tbody>';}
function visibleCols(keys=SHEET?.key_columns||{}){let preferred=[keys.reference,keys.demand,keys.status,keys.priority,keys.assignee,keys.requestor,keys.created,keys.due,keys.portfolio].filter(Boolean);let extra=(SHEET?.column_titles||[]).filter(c=>!preferred.includes(c)).slice(0,5);return [...preferred,...extra].slice(0,10)}
function renderForm(){let form=document.getElementById('addForm');form.innerHTML='';(SHEET.column_titles||[]).forEach(c=>{let d=document.createElement('div');d.innerHTML=`<label class="label">${escapeHtml(c)}</label><input name="${escapeHtml(c)}" placeholder="${escapeHtml(c)}">`;form.appendChild(d)})}
async function submitDemand(){let values={};new FormData(document.getElementById('addForm')).forEach((v,k)=>{if(v)values[k]=v});let res=await fetch('/api/rows',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})}).then(ok);let pre=document.getElementById('addResult');pre.style.display='block';pre.textContent=JSON.stringify(res,null,2);await loadAll();}
async function updateCell(rowId,col,val){await fetch(`/api/rows/${rowId}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:{[col]:val}})});} 
async function deleteRow(rowId){if(!confirm('Delete this row from Smartsheet?'))return;await fetch(`/api/rows/${rowId}`,{method:'DELETE'});await loadAll();}
async function openDemandDetail(rowId){setLoad(true);try{CURRENT_DETAIL=await fetch(`/api/rows/${rowId}`).then(ok);DETAIL_DIRTY={};renderDemandDetail();document.getElementById('detailModal').classList.add('on');await loadComments();}catch(e){alert('Could not load demand detail: '+e.message)}finally{setLoad(false)}}
function renderDemandDetail(){const d=CURRENT_DETAIL;if(!d)return;const keys=d.key_columns||{};const ref=keys.reference && d.record[keys.reference] ? d.record[keys.reference] : ('Row '+d.row_number);const titleCol=keys.demand;document.getElementById('detailTitle').textContent='Demand Detail: '+ref;document.getElementById('detailSub').textContent=(titleCol&&d.record[titleCol]?d.record[titleCol]+' · ':'')+'Row '+d.row_number+' · Modified '+(d.modified_at||'');const body=document.getElementById('detailFields');body.innerHTML=d.fields.map(f=>fieldEditor(f)).join('');const q=d.quality||{};document.getElementById('detailStatus').innerHTML='Loaded '+d.fields.length+' fields. <b>Quality:</b> '+(q.quality_score??'-')+'% · '+escapeHtml(q.readiness||'')+' · '+escapeHtml(q.confidence||'')+'<br><span class="muted">'+escapeHtml(q.reason||'Change any editable field and click Save Changes to Smartsheet.')+'</span>';}
function fieldEditor(f){const title=escapeHtml(f.title||'');const val=f.displayValue??f.value??'';const locked=f.locked;let editor='';const common=`data-title="${title}" onchange="markDirty(this)" oninput="markDirty(this)" ${locked?'disabled':''}`;
 if(f.options&&f.options.length){editor=`<select ${common}><option value=""></option>${f.options.map(o=>`<option value="${escapeHtml(o)}" ${String(o)===String(val)?'selected':''}>${escapeHtml(o)}</option>`).join('')}</select>`;}
 else if((f.type||'').includes('DATE')){let v=String(val||'').slice(0,10);editor=`<input type="date" value="${escapeHtml(v)}" ${common}>`;}
 else if((f.type||'').includes('TEXT')||String(val).length>80){editor=`<textarea ${common}>${escapeHtml(val)}</textarea>`;}
 else {editor=`<input value="${escapeHtml(val)}" ${common}>`;}
 return `<div class="field-card ${locked?'locked':''}"><label class="label">${title}</label>${editor}<div class="field-meta">Type: ${escapeHtml(f.type||'unknown')} ${locked?' · read-only':''}</div></div>`;
}
function markDirty(el){const title=el.dataset.title;DETAIL_DIRTY[title]=el.value;el.classList.add('dirty');document.getElementById('detailStatus').textContent=Object.keys(DETAIL_DIRTY).length+' unsaved change(s).';}
async function saveDemandDetail(){if(!CURRENT_DETAIL)return;const values={};for(const [k,v] of Object.entries(DETAIL_DIRTY)){values[k]=v;}if(!Object.keys(values).length){toast('No changes to save.');return;}setLoad(true);try{await fetch(`/api/rows/${CURRENT_DETAIL.row_id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})}).then(ok);toast('Saved to Smartsheet successfully.');DETAIL_DIRTY={};await reloadCurrentDetail(false);await loadAll();}catch(e){alert('Save failed: '+e.message)}finally{setLoad(false)}}
async function reloadCurrentDetail(showMsg=true){if(!CURRENT_DETAIL)return;const id=CURRENT_DETAIL.row_id;CURRENT_DETAIL=await fetch(`/api/rows/${id}`).then(ok);DETAIL_DIRTY={};renderDemandDetail();await loadComments();if(showMsg)toast('Demand detail reloaded.');}

async function loadComments(){
 if(!CURRENT_DETAIL)return;
 const status=document.getElementById('commentsStatus');const list=document.getElementById('commentsList');
 status.textContent='Loading comments...';list.innerHTML='';
 try{
   const res=await fetch(`/api/rows/${CURRENT_DETAIL.row_id}/comments`).then(ok);
   status.textContent=res.count ? `${res.count} comment(s) loaded from Smartsheet.` : 'No comments found for this demand.';
   list.innerHTML=(res.comments||[]).map(c=>`<div class="comment-item"><div class="comment-meta"><b>${escapeHtml(c.created_by||'Smartsheet User')}</b> · ${escapeHtml(c.created_at||'')}</div><div class="comment-text">${escapeHtml(c.text||'')}</div></div>`).join('');
 }catch(e){status.textContent='Could not load comments: '+e.message;}
}
async function addComment(){
 if(!CURRENT_DETAIL)return;
 const box=document.getElementById('newCommentText');const text=box.value.trim();
 if(!text){toast('Enter a comment first.');return;}
 setLoad(true);
 try{
   await fetch(`/api/rows/${CURRENT_DETAIL.row_id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})}).then(ok);
   box.value='';toast('Comment added to Smartsheet.');await loadComments();
 }catch(e){alert('Could not add comment: '+e.message)}finally{setLoad(false)}
}

function closeDetail(){if(Object.keys(DETAIL_DIRTY).length&&!confirm('Close without saving your changes?'))return;document.getElementById('detailModal').classList.remove('on');}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2600)}
function esc(s){return String(s??"").replace(/\\/g,"\\\\").replace(/'/g,"\\u0027").replace(/\r?\n/g," ")}
function escapeHtml(s){return String(s??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
loadAll();
